import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

// Ideas table - stores project ideas generated by IdeaGeneratorAgent
export const ideas = sqliteTable('ideas', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  description: text('description').notNull(),
  projectType: text('project_type', { enum: ['web-app', 'cli-tool', 'library', 'api-service'] }).notNull(),
  features: text('features', { mode: 'json' }).$type<string[]>().notNull().default('[]'),
  techStack: text('tech_stack', { mode: 'json' }).$type<string[]>().notNull().default('[]'),
  targetAudience: text('target_audience').notNull(),
  complexity: text('complexity', { enum: ['low', 'medium', 'high'] }).notNull(),
  status: text('status', { enum: ['pending', 'queued', 'in_progress', 'completed', 'failed'] }).notNull().default('pending'),
  createdAt: integer('created_at').notNull(),
  queuePosition: integer('queue_position'),
  pickedAt: integer('picked_at'),
  completedAt: integer('completed_at'),
  error: text('error'),
  metadata: text('metadata', { mode: 'json' }).$type<Record<string, unknown>>(),
});

// Projects table - stores projects being developed
export const projects = sqliteTable('projects', {
  id: text('id').primaryKey(),
  ideaId: text('idea_id').notNull().references(() => ideas.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  description: text('description').notNull(),
  type: text('type', { enum: ['web-app', 'cli-tool', 'library', 'api-service'] }).notNull(),
  status: text('status', {
    enum: ['initializing', 'generating', 'testing', 'building', 'completed', 'failed']
  }).notNull().default('initializing'),
  path: text('path').notNull(),
  gitRepo: text('git_repo'),
  version: text('version').notNull().default('0.1.0'),
  qualityScore: integer('quality_score').notNull().default(0),
  testCoverage: integer('test_coverage').notNull().default(0),
  lintErrors: integer('lint_errors').notNull().default(0),
  buildSuccess: integer('build_success', { mode: 'boolean' }).notNull().default(false),
  createdAt: integer('created_at').notNull(),
  completedAt: integer('completed_at'),
  architecture: text('architecture', { mode: 'json' }).$type<Record<string, unknown>>(),
  structure: text('structure', { mode: 'json' }).$type<Record<string, unknown>>(),
  error: text('error'),
  metadata: text('metadata', { mode: 'json' }).$type<Record<string, unknown>>(),
});

// Iterations table - stores optimization iterations for projects
export const iterations = sqliteTable('iterations', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
  type: text('type', { enum: ['feature', 'bugfix', 'refactor', 'optimization'] }).notNull(),
  title: text('title').notNull(),
  description: text('description').notNull(),
  status: text('status', { enum: ['planned', 'in_progress', 'completed', 'failed'] }).notNull().default('planned'),
  qualityBefore: integer('quality_before').notNull().default(0),
  qualityAfter: integer('quality_after'),
  filesChanged: text('files_changed', { mode: 'json' }).$type<string[]>().default('[]'),
  testCoverageBefore: integer('test_coverage_before').notNull().default(0),
  testCoverageAfter: integer('test_coverage_after'),
  createdAt: integer('created_at').notNull(),
  startedAt: integer('started_at'),
  completedAt: integer('completed_at'),
  analysis: text('analysis'),
  plan: text('plan', { mode: 'json' }).$type<Record<string, unknown>>(),
  error: text('error'),
  metadata: text('metadata', { mode: 'json' }).$type<Record<string, unknown>>(),
});

// QualityMetrics table - stores detailed quality metrics for projects
export const qualityMetrics = sqliteTable('quality_metrics', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
  timestamp: integer('timestamp').notNull(),
  codeComplexity: integer('code_complexity'),
  maintainabilityIndex: integer('maintainability_index'),
  technicalDebt: integer('technical_debt'),
  documentationCoverage: integer('documentation_coverage'),
  securityScore: integer('security_score'),
  performanceScore: integer('performance_score'),
  duplicateCodePercentage: integer('duplicate_code_percentage'),
  customMetrics: text('custom_metrics', { mode: 'json' }).$type<Record<string, unknown>>(),
});

// RuntimeState table - stores runtime state for orchestration
export const runtimeState = sqliteTable('runtime_state', {
  id: text('id').primaryKey(),
  state: text('state', { mode: 'json' }).$type<Record<string, unknown>>().notNull(),
  activeProjects: text('active_projects', { mode: 'json' }).$type<string[]>().default('[]'),
  resourceUsage: text('resource_usage', { mode: 'json' }).$type<Record<string, unknown>>(),
  lastIdeaGeneration: integer('last_idea_generation'),
  lastProjectPick: integer('last_project_pick'),
  iterationCount: integer('iteration_count').notNull().default(0),
  updatedAt: integer('updated_at').notNull(),
});

// Type exports
export type Idea = typeof ideas.$inferSelect;
export type NewIdea = typeof ideas.$inferInsert;
export type Project = typeof projects.$inferSelect;
export type NewProject = typeof projects.$inferInsert;
export type Iteration = typeof iterations.$inferSelect;
export type NewIteration = typeof iterations.$inferInsert;
export type QualityMetric = typeof qualityMetrics.$inferSelect;
export type NewQualityMetric = typeof qualityMetrics.$inferInsert;
export type RuntimeStateRecord = typeof runtimeState.$inferSelect;
export type NewRuntimeStateRecord = typeof runtimeState.$inferInsert;